In [1]:
import numpy as np

In [2]:
import pandas as pd

In [ ]:
1. Create Numpy Arrays

In [ ]:
1). Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.

In [3]:
x = [[1,2,3],[4,5,6]]
new_x = np.array(x)
print(new_x)
print(type(new_x))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
2). Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6. 

In [4]:
np.arange(1, 7).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
3). Create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.

In [5]:
x = np.arange(2,101)
print(x)
mean_x = np.mean(x)
print(mean_x)

[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]
51.0


In [ ]:
4). Create an 3x3x3 array filled with arbitrary values; and find the minimum and maximum values.

In [6]:
np.random.seed(2)
y = np.random.randint(0,100,(3,3))
print(y)
max_y = np.max(y)
min_y = np.min(y)
print("Max number in y is ", max_y, " , min number in y is ", min_y)

[[40 15 72]
 [22 43 82]
 [75  7 34]]
Max number in y is  82  , min number in y is  7


In [ ]:
5). Create a random array of size 10 and sort it.

In [8]:
np.random.seed(3)
z = np.random.randint(0,50,10)
print(z)
sorted_z = np.sort(z)
print(sorted_z)

[42 24  3  8  0 21 19 10 43 41]
[ 0  3  8 10 19 21 24 41 42 43]


In [ ]:
6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

In [9]:
x = np.arange(5, 5 + 3 * 10, 3)
print(x)

[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
7). Create an arbitrary array of shape (10,10); and find the memory size of this array.

In [10]:
np.random.seed(4)
x = np.random.randint(0,500,(10,10))
print(x)
print("Memory size of x is ", x.size * x.itemsize)

[[122 174 439 197 385 360  87 456 306 393]
 [ 58 252 359 109  94 311 439 313 360 164]
 [434  44 294 126 490  52 387   0 183  21]
 [149 201 422 486  56 194 174 373  30 136]
 [ 49 322 442 343 416 168 243 426 429 161]
 [288 126 493 412   3 370 371 207  98  95]
 [441 255  50 145 240 465 217  73 187 176]
 [460 151 114 222  22 451 190 190 331 279]
 [ 56 370 198 231 237 490 199 457 466 439]
 [181 499 240  85 478 335 292 475  59 107]]
Memory size of x is  400


In [ ]:
8). Create a null array of size 10 but the fifth value which is 1.

In [11]:
b = np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
9). Create an array with values ranging from 10 to 49; and reverse it then (first element becomes last).

In [12]:
x = np.arange(10,50)
print(x)
x = x[::-1]
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) 
     and confirm you can get the same value when you run it next time.

In [13]:
np.random.seed(5)
x = np.random.rand(3,2)
print(x)

[[0.22199317 0.87073231]
 [0.20671916 0.91861091]
 [0.48841119 0.61174386]]


In [ ]:
11). Create a 5x5 matrix with row values ranging from 0 to 4

In [14]:
x = np.zeros((5,5))
x1 = np.arange(0,5)
x = x + x1
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
12). Add a border (filled with 0's) around an existing array

In [15]:
x1 = np.ones((5,5))
x1 = np.pad(x1, pad_width=1, mode='constant',constant_values=0)
print(x1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
13). Create a 5x5 2D array with values 1,2,3,4,5 on the diagonal.

In [16]:
x = np.diag(np.arange(1,6))
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
Then, make 1,2,3,4 move below the diagonal

In [17]:
x = np.diag(np.arange(1,5), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [101]:
14). Create a 2d 10x10 array with 1 on the border and 0 inside.

In [18]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
15). Extract the integer part of a random array of positive numbers using 2 different methods, 
     and the result should be an integer array.

In [ ]:
Method1

In [19]:
x = 5.5 * np.random.random(8)
print(x)
x1 = x.astype(int)
print(x1)

[4.21249321 2.85129893 1.63240276 1.03246676 0.44407698 4.06142163
 2.42720073 0.87070427]
[4 2 1 1 0 4 2 0]


In [ ]:
Method2

In [20]:
x2 = np.array([int(i) for i in x])
print(x2)

[4 2 1 1 0 4 2 0]


In [ ]:
2. Operations on Numpy Arrays

In [ ]:
1). Find the index of 5th repetition of number 1 in the given array x.

In [21]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index_i = np.where(x == 1)[0][4]
print(index_i)

8


In [ ]:
2). Use arange to get an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order. 

In [22]:
x = np.arange(1,10)
x1, x2, x3 = x[:4],x[4:6],x[6:]
print("x1 = ", x1, ", x2 = ", x2, ", x3 = ",x3)

x1 =  [1 2 3 4] , x2 =  [5 6] , x3 =  [7 8 9]


In [ ]:
3). Use arange to generate the following 2D array
[[ 0., 1., 2., 3.],

 [ 4., 5., 6., 7.],

 [ 8., 9., 10., 11.],

 [ 12., 13., 14., 15.]]
Use np.split to split the array into left and right halves.
[[ 0,  1],

 [ 4,  5],

 [ 8,  9],

 [12, 13]]
and
[[ 2,  3],

 [ 6,  7],

 [10, 11],

 [14, 15]]

In [23]:
x = np.arange(0,16).reshape(4,4)
print(x)
np.split(x, [2], axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
4). Given an 2D array: 
    [[5,10,15],

    [20,25,30],

    [35,40,45]]

(1) Slicing to get the sub-array [[10,15], [25,30]]

(2) Getting individual element value "20"

In [24]:
x = np.arange(5,46,5).reshape(3,3)
print(x)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
(1)

In [25]:
x1 = x[:2,1:]
print(x1)

[[10 15]
 [25 30]]


In [ ]:
(2)

In [26]:
x2 = np.where(x == 20)
print("Tuple of result is :", x2)

Tuple of result is : (array([1], dtype=int64), array([0], dtype=int64))


In [ ]:
5). Let x be an array:      
    [[ 1 2 3],

     [ 4 5 6]].
    and y be an array
    [[ 7 8 9],

     [10 11 12]].
    Concatenate x and y so that a new array looks like
    [[1, 2, 3, 7, 8, 9],
     
    [4, 5, 6, 10, 11, 12]].

In [27]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
xy = np.concatenate([x, y], axis=1)
print(xy)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
6). Compute the min/max (min is divided by max) for each row for a given 2d array, 
    in which integer values range from 1 to 10 [1,10) and shape is (5,3). 
    Here requires a random seed to keep the same value from the random generator.

In [28]:
np.random.seed(6)
x = np.random.randint(1,10,(5,3))
print(x)
result = [(np.min(x[i][:]) / np.max(x[i][:])) for i in range(x.shape[0])]
print(result)

[[4 5 1]
 [2 2 5]
 [2 9 3]
 [5 3 6]
 [7 3 6]]
[0.2, 0.4, 0.2222222222222222, 0.5, 0.42857142857142855]


In [ ]:
7). Normalize a 5x5 random matrix:
    Tips: a normalization operates like: (the array - the mean)/the standard deviation

In [29]:
np.random.seed(7)
x = np.random.randint(1,20,(5,5))
print(x)
x1 = (x - np.mean(x)) / np.std(x,ddof=1)
print(x1)

[[16  5  4  8 15]
 [ 9 15 11  9  8]
 [ 7  5 17  8 13]
 [ 1 12  7 13  6]
 [17  1  3 10 15]]
[[ 1.35667365 -0.9044491  -1.11000571 -0.28777926  1.15111703]
 [-0.08222265  1.15111703  0.32889058 -0.08222265 -0.28777926]
 [-0.49333587 -0.9044491   1.56223026 -0.28777926  0.74000381]
 [-1.72667555  0.53444719 -0.49333587  0.74000381 -0.69889248]
 [ 1.56223026 -1.72667555 -1.31556232  0.12333397  1.15111703]]


In [ ]:
8). Convert 3 arrays into a 1d array. 
    arr1: 0,1,2

    arr2: 3,4,5,6

    arr3: 7,8,9
    Generate the 3 arrays by numpy arange()

    Desired Output:
    ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr1 = np.arange(0,3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
9). Get all items between 15 and 55 from aa, math expression: [15,55].
    The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). Requires defining a seed.

In [31]:
np.random.seed(88)
aa = np.random.randint(0,100,20)
print(aa)
result = [i for i in aa if ((i >= 15) & (i <= 55))]
print(result)

[88 32 79 49 20 62 97 69 48 34 97 75  4 71 90 89  7 39 70 10]
[32, 49, 20, 48, 34, 39]


In [ ]:
10). Get the positions where elements of a and b match.
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
position = [i for i in range(len(a)) if a[i] == b[i]]
print(position)

[1, 3, 5, 7]


In [ ]:
11). Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1.

In [33]:
x = np.arange(0,20)
x[x % 2 == 1] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [ ]:
12). Use two addition functions of Numpy to add every element in a 1D array of size 10 and finally get one value.; 
     and set a timer to time the two addition functions to see which one is faster.

     Tips: you can use Jupyter magic command %timeit

In [34]:
x = np.random.rand(10)
%timeit np.sum(x)
%timeit np.cumsum(x)

11.3 µs ± 799 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.97 µs ± 602 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
13). Subtract the mean of each row of a matrix X. X is a random 2D 5x10 array. 

In [35]:
np.random.seed(9)
x = np.random.randint(1,101,(5,10))
print(x)
mean_x = np.array([np.mean(x[i]) for i in range(x.shape[0])]).reshape(5,1)
print(mean_x)
result = x - mean_x
print(result)

[[ 93  55  57  23  66  23  53  60  41  92]
 [ 34  94  93   1  61  60  89  75  57  94]
 [ 63  13  19  87  57   2  57 100  12  38]
 [ 20  10  81  57  50  64  14  60  59  34]
 [ 78  94  55  64  23  51  41   5 100  53]]
[[56.3]
 [65.8]
 [44.8]
 [44.9]
 [56.4]]
[[ 36.7  -1.3   0.7 -33.3   9.7 -33.3  -3.3   3.7 -15.3  35.7]
 [-31.8  28.2  27.2 -64.8  -4.8  -5.8  23.2   9.2  -8.8  28.2]
 [ 18.2 -31.8 -25.8  42.2  12.2 -42.8  12.2  55.2 -32.8  -6.8]
 [-24.9 -34.9  36.1  12.1   5.1  19.1 -30.9  15.1  14.1 -10.9]
 [ 21.6  37.6  -1.4   7.6 -33.4  -5.4 -15.4 -51.4  43.6  -3.4]]


In [ ]:
14) Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once? 

In [36]:
np.random.seed(10)
a = np.random.randint(0,10,(3,4,3,4))
sum_a = a.sum(axis=(-2,-1))
print(sum_a)

[[55 48 69 53]
 [72 53 49 34]
 [43 36 69 75]]


In [ ]:
15). Use np.put to randomly place 3 numbers (which can be any value, like 5) in a 2D 10x10 zero array:

Tips: here, randomly placing 3 numbers means you should first randomly generate the indices of the 3 numbers in the 2D 10x10 array.

In [37]:
np.random.seed(11)
x = np.zeros(100).reshape(10,10).astype(int)
positions = np.random.choice(range(10*10),3,replace=False)
np.put(x,positions,np.random.randint(50,100,3))
print(x)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0 60  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 67  0  0 54]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [ ]:
3. Indexing and Slicing

In [ ]:
1) Given a 1d array: [ 3, 6, 9, 25, 10, 8] 
    
    (1) To get all elements except the first:

    (2) To get all elements except the last:

    (3) To get every other element of the array (operation from the first element):

    (4) To reverse the array:

In [38]:
x = np.array([ 3, 6, 9, 25, 10, 8])

In [ ]:
(1)

In [39]:
x1 = x[1:]
print(x1)

[ 6  9 25 10  8]


In [ ]:
(2)

In [40]:
x2 = x[:len(x)-1]
print(x2)

[ 3  6  9 25 10]


In [ ]:
(3)

In [41]:
x3 = x[::2]
print(x3)

[ 3  9 10]


In [ ]:
(4)

In [42]:
x4 = x[::-1]
print(x4)

[ 8 10 25  9  6  3]


In [ ]:
2) Multidimensional Arrays: 
(1) create an array with the components as 0-31 and the shape is (8,4).

(2) set the 3rd element in the 1st row to 0.

(3) print out the second column.

(4) Get the 3x3 region from the array:

([ 9, 10, 11],

 [13, 14, 15],

 [17, 18, 19]])

In [ ]:
(1)

In [43]:
x = np.arange(0,32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
(2)

In [44]:
x[0][2] = 0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
(3)

In [45]:
print(x[1])

[4 5 6 7]


In [ ]:
(4)

In [46]:
x1 = x[2:5,1:]
print(x1)

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [ ]:
3) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 
   Please use the numpy "slicing" method to realize.  
    [[0. 1. 0. 1.]

    [1. 0. 1. 0.]

    [0. 1. 0. 1.]

    [1. 0. 1. 0.]]
    If students use other methods to get the same result, TA only can give half of the points.

In [47]:
x = np.ones((4,4))
x[::2,::2] = 0
x[1::2,1::2] = 0
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [ ]:
4) Swap the first two rows of the array: aa = np.arange(20).reshape(5,4)

In [48]:
aa = np.arange(20).reshape(5,4)
aa[[0,1], :] = aa[[1,0], :]
print(aa)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
4. Broadcasting in Practice

In [ ]:
1) Given 2 arrays:    
    a_2d : [[3,3,3],[4,4,4],[5,5,5]]

    b_1d : [1,2,3]
    Do the subtraction so that the result is:
    [[2 2 2]

    [2 2 2]

    [2 2 2]]

In [49]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
b_1d = b_1d.reshape(3,1)
result = a_2d - b_1d
print(result)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
2). Write a 6x6 matrix for multiplication table:  
    - by using numpy broadcasting (4 points)

    - by using Python nested for-loop (4 points).
    Desired output:
        array([[ 1,  2,  3,  4,  5,  6],

       [ 2,  4,  6,  8, 10, 12],

       [ 3,  6,  9, 12, 15, 18],

       [ 4,  8, 12, 16, 20, 24],

       [ 5, 10, 15, 20, 25, 30],

       [ 6, 12, 18, 24, 30, 36]])

In [ ]:
 - by using numpy broadcasting

In [50]:
x = np.arange(1,7)
y = np.arange(1,7).reshape(6,1)
result = x * y
print(result)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [ ]:
- by using Python nested for-loop (4 points).

In [51]:
result = np.array([i*j for i in range(1,7) for j in range(1,7)]).reshape(6,6)
print(result)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [ ]:
3) For an arbitrary array of dimension (5,5,3), consider multiplying it by an arbitrary array with dimensions (5,5). 

In [52]:
np.random.seed(13)
x = np.random.randint(1,500,(5,5,3))
x1 = np.random.randint(1,50,(5,5))
x1 = x1.reshape(5,5,1)
result = x * x1
print(result)

[[[ 6780  3540  1500]
  [  102  1386  2130]
  [  245   154   237]
  [ 9746 10648  9042]
  [11760  6096 21648]]

 [[11206 11414  5980]
  [21252  3450 15180]
  [13944 12978 10878]
  [ 5796 14544  5400]
  [ 1212   420  1413]]

 [[ 1368    36  2646]
  [ 8149 11977   348]
  [ 2673  2997  2835]
  [  874 11058  6878]
  [ 5236  6832  6776]]

 [[18720  5808  8640]
  [ 2274  2070  1284]
  [ 7956   650  6656]
  [  228   860   656]
  [ 6664  2108  4471]]

 [[ 6912  6588 12528]
  [ 2744  1336  3744]
  [ 9963  3753  7587]
  [17568 13392 15264]
  [ 7067 15577  8251]]]


In [ ]:
Others: 

In [ ]:
1) Find the closest value from a given value 0.5 in an arbitrary array with values 0-1. 5 points

In [54]:
np.random.seed(13)
x = np.random.rand(10)
result = x[np.argmin(np.abs(x-0.5))]
print(x)
print(result)

[0.77770241 0.23754122 0.82427853 0.9657492  0.97260111 0.45344925
 0.60904246 0.77552651 0.64161334 0.72201823]
0.4534492474173122


In [ ]:
2) Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 
how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?    5 points

Hint: from numpy.lib import stride_tricks

In [55]:
from numpy.lib import stride_tricks

In [56]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
result = stride_tricks.as_strided(Z, (len(Z)-3, 4), (Z.itemsize, Z.itemsize))
print(result)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
